AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Storygraf backend API
Globals:
  Function:
    Timeout: 3
Resources:
  ExpressApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
  ExpressLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables: null
      CodeUri: s3://storygraf-backend/17defd53b7c7364c6ebad91e358097de
      Handler: lambda.handler
      MemorySize: 512
      Runtime: nodejs14.x
      Timeout: 30
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: ExpressApi
            Path: /
            Method: ANY
            cors: true
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId:
              Ref: ExpressApi
            Path: /{proxy+}
            Method: ANY
            cors: true
